lenguage: ruby
rvm:
- 2.3.0
script: bundle exec rspec
addons:
  code_climate:
    repo_token:
      secure: ibrwCWOMwkhCh0HWnKIFpciJQDT7SLe9Qu3ztT7c4JE0341AGkZZTBzo1KZ4THsKkBopySRzdx2AzW7TSImHd4Do+rQ3cumHuaFI4slevNl9blHKpOGOqWB/8wrwo9vNZb4h3zhhbSD4dp9IhxQ8yxK9jtOX3ZJYlQPWlTCIyNHX4P8ydi+bYz6vHfC6J8vIHhwIMKtKSWQ+H+oqIx/KsptjZBqN9tW5iVXpUkD6y4qoVBx4wu0UYdilH9w/zn+ky2UhWpBy+/w60BbtsgSGhnb+CWVeiiOJGzs0jLYQa/nOZgIOtPe7pRqhOFBzeWiGIvAA9LZyGVW6sc78e4bXDUPmF1O3kCRcWfvqOUmxvZPSFQUC9Wh+/pEJjBVpzCq46G2oY0ccJCiGqhL+t4behshD+NTgPSfbUM57hW81hoXsYfnXuXaXy2yvEVzT4WcExqBeQnznHlot5btMFz3X3kKoyr3oQSL05ZrcUBDYC3SMKe+kCUqtzRWEI0zgkJqauM/E+qQPg4kTBtnpWLsWcrA7chweXG55aGnn/h3IGaqU1VJtKYuNG5ZHFYutSgcC/yYJgd5ixVUPjQn0ITeabm4NHU2H+CC74I5anvcT88habWXJvoqXw2AnMoqLuUpc19v/1ywjA/6qXam1H/Rjc9Sl30R8oh7s2BNZlR+hjKg=
